Fix dmenu_script with the help of shellcheck

diff --git a/script/dmenu_saro b/script/dmenu_saro
--- a/script/dmenu_saro
+++ b/script/dmenu_saro
@@ -1,58 +1,78 @@
 #!/bin/bash
 
-cache="/tmp/dmenu_cache"
-history_file="/home/saro/dmenu_hist"
-running="/tmp/dmenu_running"
+# DMENU scrupt
+
+# Variables
+TMP_DIR="/tmp"
+
+cache="${TMP_DIR}/dmenu_cache"
+history_file="$HOME/dmenu_hist"
+running="${TMP_DIR}/dmenu_running"
 
 if [[ ! -e ${history_file} ]] ; then
-	touch ${history_file}
+	touch "${history_file}"
 fi
 
 
-if [[ "/home/saro/.gtk-bookmarks" -nt $cache || ! -e /tmp/dmenu_cache  || "/usr/share/applications" -nt $cache ]] ; then 
+if [[ "/home/saro/.gtk-bookmarks" -nt $cache || ! -e /tmp/dmenu_cache  || \
+	"/usr/share/applications" -nt $cache || "$HOME/.local/share/applications" -nt $cache ]]; then
 
+	# Reset cache file
 	echo "" > $cache
-	for i in $(cat ~/.gtk-bookmarks); do
+	grep -v '^ *#' < "${HOME}/.gtk-bookmarks" | while IFS= read -r i; do
 		echo "${i##*/}_dir" >> $cache
 	done;
 
-	for i in $(ls /usr/share/applications/*.desktop); do
-		basename $i .desktop >> $cache
+	for i in ~/.local/share/applications/*.desktop; do
+		basename "$i" .desktop >> $cache
 	done
 
-	for i in $(ls /usr/local/share/applications/*.desktop); do
-		basename $i .desktop >> $cache
+	for i in /usr/share/applications/*.desktop; do
+		basename "$i" .desktop >> $cache
+	done
+
+	for i in /usr/local/share/applications/*.desktop; do
+		basename "$i" .desktop >> $cache
 	done
 fi
 
-cat ${history_file} > $running
+cat "${history_file}" > $running
 cat $cache >> $running
 
 result=$(dmenu -b -i "$@" -fn 'Droid Sans Mono-12'< $running)
 
 err=0
+desktopfile=""
+
 if [[ $result != "" ]] ; then
 	itsdir=".*_dir$"
 	if [[ $result =~ $itsdir ]] ; then
-		echo " DIR: $(cat ~/.gtk-bookmarks| awk {'print $1'}|grep ".*/${result%_dir}$"| head -n1)"
-		thunar "$(cat ~/.gtk-bookmarks| awk {'print $1'}|grep ".*/${result%_dir}$"| head -n1)"
+		# echo " DIR: $(cat ~/.gtk-bookmarks| awk {'print $1'}|grep ".*/${result%_dir}$"| head -n1)"
+		thunar "$(awk '{print $1}' ~/.gtk-bookmarks |grep ".*/${result%_dir}$"| head -n1)"
 	else
-		if [[ ! -e  /usr/share/applications/${result}.desktop ]] ; then
-			err = 1
+		if [[ -e  ~/.local/share/applications/${result}.desktop ]]; then
+			desktopfile="$HOME/.local/share/applications/${result}.desktop"
+		elif [[ -e  /usr/share/applications/${result}.desktop ]]; then
+			desktopfile="/usr/share/applications/${result}.desktop"
+		elif [[ -e  /usr/local/share/applications/${result}.desktop ]]; then
+			desktopfile="/usr/local/share/applications/${result}.desktop"
+		else
+			err=1
 		fi
-		desktopfile=$(cat /usr/share/applications/${result}.desktop)
-		if [[ $desktopfile == "" ]] ; then
-			desktopfile=$(cat /usr/local/share/applications/${result}.desktop)
+
+		if [[ $err != "1" ]]; then
+			ex=$(grep "Exec=" "$desktopfile"|sed 's/^.*Exec=//'|head -n1|sed 's/%.*//')
+			echo "DESKTOP: $desktopfile  EXEC: $ex"
+			${ex}&
+		else
+			echo "ERROR"
+			exit 1
 		fi
-		ex=$(echo "$desktopfile"|grep "Exec="|sed 's/^.*Exec=//'|head -n1|sed 's/%.*//')
-		echo " EXEC: $ex"
-		${ex}&
 	fi
 
 	if [[ $err -eq 0 ]]; then
-		hist=$(cat ${history_file})
-		echo "${result}
-$hist" | awk '!x[$0]++' > ${history_file}
+		hist=$(cat "${history_file}")
+		printf "%s\n%s" "${result}" "$hist" | awk '!x[$0]++' > "${history_file}"
 	fi
 fi
 
